name:                BullsAndCows
version:             0.1.0.0
github:              "pikapikapikachuuu/BullsAndCows"
license:             BSD3
author:              "pikachu"
maintainer:          "hooraypikachu@gmail.com"
copyright:           "2018 pikachu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pikapikapikachuuu/BullsAndCows#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  BullsAndCows-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BullsAndCows

tests:
  BullsAndCows-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BullsAndCows
